[package]
name = "nerf-burn"
authors = ["mistgc <georgecai0908@outlook.com>"]
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
burn = { version = "0.15.0", features = ["wgpu", "dataset"] }
image = "0.25.5"
rand = "0.8.5"
rayon = "1.10.0"
serde = "1.0.215"
serde_json = "1.0.133"
